import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { PartnerRegisterForm } from '../components/PartnerRegisterForm.js';
import { TechnicianLoginForm } from '../components/TechnicianLoginForm.js';
import { TwoFactorSettings } from '../components/TwoFactorSettings.js';
import { ViewerSessionCard } from '../components/ViewerSessionCard.js';
import { api, ApiError, type PartnerOffer, type ViewerSession } from '../lib/api.js';

interface PartnerMe { partner:{id:string;fullName:string;username:string;businessName:string|null;totpEnabled:boolean}; offer:PartnerOffer; }
type Tab='overview'|'sessions'|'security';
export function PartnerPage(){
 const [token,setToken]=useState<string|null>(localStorage.getItem('tech_assist_token'));const [loginTab,setLoginTab]=useState<'login'|'register'>('login');const [me,setMe]=useState<PartnerMe|null>(null);const [sessions,setSessions]=useState<ViewerSession[]>([]);const [fetchedAt,setFetchedAt]=useState(Date.now());const [label,setLabel]=useState('');const [error,setError]=useState<string|null>(null);const [blocked,setBlocked]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [tab,setTab]=useState<Tab>('overview');const timer=useRef<ReturnType<typeof setInterval>|null>(null);
 const logout=useCallback(()=>{localStorage.removeItem('tech_assist_token');setToken(null);setMe(null);setSessions([]);setBlocked(null);},[]);
 const loadMe=useCallback(async()=>{try{setMe(await api.get<PartnerMe>('/api/partner/me'));setBlocked(null);}catch(e){if(e instanceof ApiError&&e.status===401)logout();else if(e instanceof ApiError&&e.status===403)setBlocked("Ce compte n'est pas un compte partenaire actif.");else setError('Impossible de charger votre espace.');}},[logout]);
 const refreshSessions=useCallback(async()=>{try{const res=await api.get<{sessions:ViewerSession[]}>('/api/partner/viewer-sessions');setSessions(res.sessions);setFetchedAt(Date.now());}catch(e){if(e instanceof ApiError&&e.status===401)logout();}},[logout]);
 useEffect(()=>{if(token)void loadMe();},[token,loadMe]);
 const hasOpen=sessions.some(s=>s.state!=='ended');
 useEffect(()=>{if(!token||!me)return;void refreshSessions();timer.current=setInterval(()=>void refreshSessions(),hasOpen?4000:20000);return()=>{if(timer.current)clearInterval(timer.current);};},[token,me,hasOpen,refreshSessions]);
 const stats=useMemo(()=>({open:sessions.filter(s=>s.state!=='ended').length,paid:sessions.filter(s=>s.paid).length,waiting:sessions.filter(s=>s.state==='waiting_payment').length}),[sessions]);
 async function openSession(e:React.FormEvent){e.preventDefault();setBusy(true);setError(null);try{await api.post('/api/partner/viewer-sessions',{label:label||undefined});setLabel('');setTab('sessions');await refreshSessions();}catch(e){setError(e instanceof ApiError?e.message:'Impossible d’ouvrir la session.');}finally{setBusy(false);}}
 if(!token)return <div className="min-h-[78vh] bg-slate-50 flex items-center"><div className="ta-container max-w-md w-full"><div className="overflow-hidden rounded-[2rem] border bg-white shadow-2xl"><div className="bg-slate-950 p-8 text-white"><p className="text-[11px] font-black uppercase tracking-[.24em] text-slate-400">TECH ASSIST / PARTNER</p><h1 className="mt-3 text-3xl font-black">Votre atelier de support à distance.</h1><p className="mt-3 text-sm leading-6 text-slate-300">Ouvrez une session, donnez le code à votre client et pilotez l’intervention depuis une console unique.</p></div><div className="p-8"><div className="mb-5 grid grid-cols-2 gap-1 rounded-xl bg-slate-100 p-1 text-sm font-bold"><button onClick={()=>setLoginTab('login')} className={'rounded-lg py-2 '+(loginTab==='login'?'bg-white shadow-sm':'text-slate-500')}>Connexion</button><button onClick={()=>setLoginTab('register')} className={'rounded-lg py-2 '+(loginTab==='register'?'bg-white shadow-sm':'text-slate-500')}>Créer un compte</button></div>{loginTab==='login'?<TechnicianLoginForm onLoggedIn={t=>{localStorage.setItem('tech_assist_token',t);setToken(t);}}/>:<PartnerRegisterForm/>}<Link to="/" className="mt-4 block text-center text-sm text-slate-500 hover:underline">Retour au site</Link></div></div></div></div>;
 if(blocked)return <div className="ta-container max-w-md py-14"><div className="ta-card space-y-4 p-6"><p className="font-semibold">{blocked}</p><button onClick={logout} className="ta-button-secondary w-full">Changer de compte</button></div></div>;
 const price=me?.offer.priceFcfa??null;
 return <div className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="ta-container max-w-7xl py-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[11px] font-black uppercase tracking-[.24em] text-brand-700">TECH ASSIST / PARTNER</p><h1 className="mt-1 text-2xl font-black">{me?.partner.businessName||me?.partner.fullName||'Mon espace partenaire'}</h1><p className="text-sm text-slate-500">@{me?.partner.username}</p></div><div className="flex gap-2"><button onClick={()=>void refreshSessions()} className="rounded-xl border px-4 py-2 text-sm font-bold">Actualiser</button><button onClick={logout} className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-bold text-white">Déconnexion</button></div></div></div></header>
 <main className="ta-container max-w-7xl py-6 sm:py-8">{error&&<div className="mb-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}
 <nav className="mb-6 flex gap-2 overflow-x-auto rounded-2xl border bg-white p-2 shadow-sm">{[['overview','Vue d’ensemble'],['sessions','Sessions'],['security','Sécurité']].map(([id,labelText])=><button key={id} onClick={()=>setTab(id as Tab)} className={'shrink-0 rounded-xl px-4 py-2.5 text-sm font-bold '+(tab===id?'bg-slate-950 text-white':'text-slate-500 hover:bg-slate-50')}>{labelText}</button>)}</nav>
 {tab==='overview'&&<div className="space-y-6"><section className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-slate-950 p-5 text-white"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Sessions ouvertes</p><p className="mt-2 text-4xl font-black">{stats.open}</p></div><div className="rounded-2xl border bg-white p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Sessions payées</p><p className="mt-2 text-4xl font-black">{stats.paid}</p></div><div className="rounded-2xl border bg-white p-5"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Paiements à finaliser</p><p className="mt-2 text-4xl font-black">{stats.waiting}</p></div></section>
 {!me?.partner.totpEnabled&&<section className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><p className="font-black text-amber-950">Activez la double authentification avant toute intervention.</p><p className="mt-1 text-sm text-amber-900">Le compte partenaire donne accès aux ordinateurs de vos clients.</p><button onClick={()=>setTab('security')} className="mt-4 rounded-xl bg-amber-950 px-4 py-2 text-sm font-bold text-white">Sécuriser mon compte</button></section>}
 {me?.partner.totpEnabled&&<section className="rounded-[1.5rem] border bg-white p-6 shadow-sm"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h2 className="text-lg font-black">Nouvelle intervention</h2><p className="text-sm text-slate-500">Inclus : {Math.round((me.offer.freeSeconds??180)/60)} min · puis {price!==null?price.toLocaleString('fr-FR')+' FCFA':'tarif selon offre'}.</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-black text-emerald-700">2FA ACTIVE</span></div><form onSubmit={openSession} className="mt-5 flex flex-col gap-3 sm:flex-row"><input placeholder="Nom du client (facultatif)" value={label} onChange={e=>setLabel(e.target.value)} maxLength={120} className="ta-input flex-1"/><button disabled={busy} className="ta-button-primary disabled:opacity-60">{busy?'Ouverture…':'Ouvrir une session'}</button></form></section>}
 <section className="rounded-[1.5rem] border bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-black">Dernières sessions</h2><p className="text-sm text-slate-500">Actualisation automatique quand une session est active.</p></div><button onClick={()=>setTab('sessions')} className="text-sm font-bold text-brand-700">Tout voir →</button></div><div className="mt-4 space-y-3">{sessions.slice(0,3).map(s=><ViewerSessionCard key={s.id} session={s} methods={me?.offer.methods??[]} priceFcfa={price} fetchedAt={fetchedAt} onChanged={()=>void refreshSessions()}/>)}{sessions.length===0&&<p className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">Aucune session.</p>}</div></section></div>}
 {tab==='sessions'&&<section className="rounded-[1.5rem] border bg-white p-6 shadow-sm"><h2 className="text-lg font-black">Toutes les sessions</h2><p className="text-sm text-slate-500">Suivez le statut, l’autorisation client et le paiement.</p><div className="mt-5 space-y-3">{sessions.length?sessions.map(s=><ViewerSessionCard key={s.id} session={s} methods={me?.offer.methods??[]} priceFcfa={price} fetchedAt={fetchedAt} onChanged={()=>void refreshSessions()}/>):<p className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">Aucune session.</p>}</div></section>}
 {tab==='security'&&<div className="grid gap-6 lg:grid-cols-2"><section className="rounded-[1.5rem] border bg-white p-6 shadow-sm"><h2 className="text-lg font-black">Double authentification</h2><p className="mt-2 text-sm text-slate-500">Protection obligatoire pour accéder aux postes clients.</p><div className="mt-5"><TwoFactorSettings onEnabled={()=>void loadMe()}/></div></section><section className="rounded-[1.5rem] border bg-white p-6 shadow-sm"><h2 className="text-lg font-black">Compte partenaire</h2><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-slate-500">Nom</dt><dd className="font-bold">{me?.partner.fullName}</dd></div><div><dt className="text-slate-500">Identifiant</dt><dd className="font-bold">{me?.partner.username}</dd></div><div><dt className="text-slate-500">Entreprise</dt><dd className="font-bold">{me?.partner.businessName||'Indépendant'}</dd></div><div><dt className="text-slate-500">Offre</dt><dd className="font-bold">{price!==null?price.toLocaleString('fr-FR')+' FCFA / session':'—'}</dd></div></dl></section></div>}
 </main></div>;
}